#!/usr/bin/zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="btop,hypr,nvim,tmux,wezterm"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
