#!/usr/bin/zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,btop,hypr,nvim,swaylock,tmux,waybar,wezterm,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
